version: '2.15.1'

services:
  db1:
    image: postgres:alpine
    restart: always
    container_name: yom-db-development
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: yom-db-development

  db2:
    image: postgres:alpine
    restart: always
    container_name: yom-db-tests
    ports:
      - '5433:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: yom-db-tests
